### ISSUE TITLE
运行报错各位有遇到过么（）

### ISSUE THREAD

**Issue by lemo-kk** [marunrun/showstart-checkout#32]
chunk-RCPA6UVN.js:1 Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    at chunk-RCPA6UVN.js:1:542
    at new Promise (<anonymous>)
    at c (chunk-RCPA6UVN.js:1:397)
    at a (chunk-HNLFKTAJ.js:1:68)
    at d2 (chunk-YIDC66OP.js:2:542)
    at y (chunk-YIDC66OP.js:2:684)
    at post (http.ts:51:5)
    at http.ts:17:1

**Comment by marunrun** [comment]
2.x 版本使用 [tauri](https://github.com/tauri-apps/tauri) 开发
